### ISSUE TITLE
Error on running the tool

### ISSUE THREAD

**Issue by B4RD4k** [ring0lab/catphish#1]
Hello, when i'm trying to run the tool i'm getting this error message can you please assist?
10x

/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- simpleidn (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from catphish.rb:14:in `<main>'

**Comment by alexpeleg** [comment]
having the same issue.

**Comment by Dviros** [comment]
working for me
did you run the following?
gem install simpleidn whois whois-parser

**Comment by B4RD4k** [comment]
after installing, work :)

**Comment by strazzere** [comment]
Correct - you just need to make sure you do a gem install on all the imports for this project. What @Dviros mentioned should suffice or what I had to do;

`gem install resolv simpleidn whois whois-parser`

**Comment by picatz** [comment]
@ring0lab I think the best thing that could be done to solve the dependency issues for the tool would be to bundle it up as a ruby gem and have those dependencies managed when a user installs the tool through something like:

```shell
$ gem install catphish
```

I'm working a refactor of catphish right now which I could bundle up and maintain as a separate project if you don't want to do that. But, I think it would be worth looking into.

**Comment by ring0lab** [comment]
@picatz Thanks for your suggestion, this is a great idea. We will look into this and let you later.
