### ISSUE TITLE
How you create this logo?

### ISSUE THREAD

**Issue by renatotavares** [ring0lab/catphish#3]
I was curious to know which tool you used to create the logo. How did you create it?

**Comment by picatz** [comment]
I didn't create it, but I've done several ascii art related stuff. 

The logo seems to be done in an **ANSI Shadow** font style. 

This type of thing can be generated for you on several websites if you look up "text to ASCII art".

```shell
██████╗ ██╗ ██████╗ █████╗ ████████╗
██╔══██╗██║██╔════╝██╔══██╗╚══██╔══╝
██████╔╝██║██║     ███████║   ██║   
██╔═══╝ ██║██║     ██╔══██║   ██║   
██║     ██║╚██████╗██║  ██║   ██║   
╚═╝     ╚═╝ ╚═════╝╚═╝  ╚═╝   ╚═╝   
A little example.
```
