### ISSUE TITLE
Structural Overhaul and Rainbows?

### ISSUE THREAD

**Issue by picatz** [ring0lab/catphish#4]
# Structural Overhaul for Even More 🌞  and 🌈s
I made some changes that I think help modularize the codebase a little more and can allow for easier testing of the individual parts of the application ( which I haven't added ). 

➡️  [**This is what I did**](https://github.com/picatz/catphish/blob/house-cleaning/catphish.rb).

I also detail some of the changes further in the [commit details](https://github.com/picatz/catphish/commit/6fe98e3754b0530575e6e961fcdd9211468923be), but, I probably should've just broken them up into smaller commits for that branch. _Oh well._ 
##### Small Confession & Thought
There's also some comments left in there that I will clean up in a little bit after posting this. Probably could even add some more documentation comments in [yardoc](http://yardoc.org/) style or something. Because that way it'll look better when it's published as a gem to rubygems.

_Speaking of that..._

## 💎  Let's Gemify Catphish 
There's plenty of tutorials online for how to do this. 

- If you want to do that: cool. 
- If you don't want to: I can do that no problem.

#### Solving the Dependency Issues
Because [some people have had problems with the other gems this application relies on not being on their system](https://github.com/ring0lab/catphish/issues/1) -- we should just manage that for them by bundling it up as a pretty gem. 

The dependency specifications can be laid out simply in the catphish application gempsec ( which doesn't exist yet ) and that can be taken care of much simpler. And then hopefully that issue doesn't happen for anyone else -- _like myself_  😺 -- **ever** again.

## 🌈 Rainbow Option
I haven't added this yet. But, that'll be super easy to add.

**Comment by ring0lab** [comment]
@picatz Any benefits from using trollop instead of GetoptLong?

**Comment by picatz** [comment]
## Maybe
@ring0lab I think there is a certain when clarity using trollop in some cases. In general, I believe it reads pretty decently. Perhaps I'd call it a bit more "ruby-like" in some ways, but that's just some opinion stuff that might be best to be ignored in favor of the clarity argument. But, that's also a bit subjective.

There's also some stuff you get for free while using trollop that I think is pretty handy. A usage menu, a pretty smart and easy to use API to describe the ( command-line ) interface. Other rubyists are generally pretty used to trollop. I think it simplifies a lot of stuff and is really easy to lean on to do some of the boring stuff for command-line parsers while doing it more than half-way decently with a few minor edge cases that are hardly a problem.

Granted, as I've mentioned, it's far from perfect. It's just very simple to implement. 

## Speaking of Stuff
Also. One could argue that a better solution could be to just follow suite with many applications such as bettercap and just use `require 'optparse'` which is "much more advanced, yet also easier to use, than GetoptLong, and is a more Ruby-oriented solution."[[*](https://ruby-doc.org/stdlib-2.1.1/libdoc/optparse/rdoc/OptionParser.html)] 

**Honestly, while writing this. That _might_ just be the best solution.** I'd give it a quick looksie.

## Make it Easy
If using `trollop` or `optparse` make it more annoying for you to work on the code base ( or anyone else that would want to chime in for or against ), then _I don't really_ mind using the **longest of opts that I have to get** to get the job done to make things go as smooth as possible. 👍
